version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
